name = "RollOverData"
uuid = "8e5f5ac9-b367-4c09-ba43-dee536866b7a"
repo = "github.com/JeffreySarnoff/RollOverData.jl.git"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>", "other contributors"]
license = "MIT"
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Distances= "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"	
VectorizedStatistics = "3b853605-1c98-4422-8364-4bd93ee0529e"
Accumulators = "dfa2bc4b-4f41-456b-b06b-8999b58af168"
MovingRings = "3594f790-2b65-4114-995e-a369a7faa39f"

[compat]
StatsBase = "0.33, 0.34, 0.35, 0.36"
Distances = "0.10, 0.11, 0.12"
VectorizedStatistics = "0.4, 0.5, 0.6, 0.7"
Accumulators = "0.1, 0.2, 0.3"
MovingRings = "0.1, 0.2. 0.3"
julia = "1.8"

[extras]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StatsBase", "Test"]

